### ISSUE TITLE
开发模式闪退，Error: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by jahentao** [aliyun/oss-browser#194]
Windows Git Bash下执行`make run`开发模式闪退。`Error: EBUSY: resource busy or locked, open 'F:\Workspace\GitHub\oss-browser\dist\node\crc64\electron-crc64-prebuild\lib\win32-x64\Release\crc64_ecma182.node'`怎么解决？

```gitbash
√ Installed 10 packages
√ Linked 0 latest versions
√ Run 0 scripts
√ All packages installed (used 16ms(network 13ms), speed 0B/s, json 0(0B), tarball 0B)
--done
--done
--done
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, open 'F:\Workspace\GitHub\oss-browser\dist\node\crc64\electron-crc64-prebuild\lib\win32-x64\Release\crc64_ecma182.node'
Emitted 'error' event at:
    at next (F:\Workspace\GitHub\oss-browser\node_modules\_map-stream@0.1.0@map-stream\index.js:75:19)
    at F:\Workspace\GitHub\oss-browser\node_modules\_map-stream@0.1.0@map-stream\index.js:85:7
    at done (F:\Workspace\GitHub\oss-browser\node_modules\_vinyl-fs@0.1.4@vinyl-fs\lib\dest\writeContents.js:7:5)
    at fs.js:1170:7
    at OpenReq.Req.done (F:\Workspace\GitHub\oss-browser\node_modules\_graceful-fs@2.0.3@graceful-fs\graceful-fs.js:143:5)
    at OpenReq.done (F:\Workspace\GitHub\oss-browser\node_modules\_graceful-fs@2.0.3@graceful-fs\graceful-fs.js:63:22)
    at FSReqWrap.oncomplete (fs.js:141:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oss-browser@1.9.1 build: `gulp build --custom=$custom`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oss-browser@1.9.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jahentao\AppData\Roaming\npm-cache\_logs\2019-01-18T05_26_58_816Z-debug.log
ERROR: "build" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oss-browser@1.9.1 dev: `npm-run-all --parallel build watch dev:run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oss-browser@1.9.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jahentao\AppData\Roaming\npm-cache\_logs\2019-01-18T05_26_59_131Z-debug.log
make: *** [makefile:25: run] Error 1

```

闪退效果图

![闪退](https://images-markdown.oss-cn-hangzhou.aliyuncs.com/problems/oss-browser%E9%97%AA%E9%80%80.gif)

**Comment by jahentao** [comment]
斗胆将`'F:\Workspace\GitHub\oss-browser\dist\node\crc64\electron-crc64-prebuild\lib\win32-x64\Release\crc64_ecma182.node'`删除了，试了一下，不会闪退了。那么，为什么会产生这个`*.node`文件，造成闪退的原因是什么？

**Comment by luozhang002** [comment]
@jahentao 目前我在MAC在我本地编译并未出现闪退，均能够重新编译，这个node文件是引入的一个C++模块crc64编译出来的，因为我们上传后要做一次crc64 check，所以引用了C++的一个crc64模块，效率会高一点。

**Comment by jahentao** [comment]
**发现一个奇怪的现象**
在Windows 10 Git Bash中重新编译运行
```
make clean
make i
make run
```
当执行`make run`它会弹出

![Error](https://images-markdown.oss-cn-hangzhou.aliyuncs.com/problems/Error%20launching%20app.png)

这个错误弹出，`make run`仍在执行，必须在出现`done ... done... done... node gen`之后点错误框的确定，否则下次`make run`还会弹出错误框。

![Error解决时机](https://images-markdown.oss-cn-hangzhou.aliyuncs.com/problems/Error%20launching%20app%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95.png)

**Comment by Ari1c** [comment]
你之前在windows上面make run 之后遇到的闪退问题有解决？

**Comment by jahentao** [comment]
> 你之前在windows上面make run 之后遇到的闪退问题有解决？

不太记得了，不够，我记得摸索一下，还是可以的

**Comment by AmFanyuxi** [comment]
楼主还记得如何解决么?

**Comment by JimEverest** [comment]
问题依然存在

**Comment by AmFanyuxi** [comment]
范宇茜  Fanyuxi软件工程师 ｜ ***@***.***    |  ***@***.***地址：贵州省观山湖区  |科技｜创新｜学习｜开放｜价值 | 创造
