### ISSUE TITLE
Ubuntu 19.10 无法运行

### ISSUE THREAD

**Issue by eallion** [aliyun/oss-browser#281]
Ubuntu 19.10 无法运行 没任何反应

**Comment by eallion** [comment]
```
./oss-browser
```
```
Gtk-Message: 20:36:13.096: Failed to load module "canberra-gtk-module"
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-log'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/home/eallion/Downloads/oss-browser-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/eallion/Downloads/oss-browser-linux-x64/resources/app.asar/main.js:15:11)
    at Object.<anonymous> (/home/eallion/Downloads/oss-browser-linux-x64/resources/app.asar/main.js:289:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

```

**Comment by PeterRao** [comment]
下载 https://help.aliyun.com/document_detail/61872.html?spm=5176.8465980.0.0.4e701450Kn7Wve 试下。
