### ISSUE TITLE
Mac 10.13.6 无法启动，Error: Cannot find module 'electron-log'

### ISSUE THREAD

**Issue by Vidtion** [aliyun/oss-browser#289]
`A JavaScript error occurred in the main process`

```
Uncaught Exception:
Error: Cannot find module 'electron-log'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/private/var/folders/ds/m1z5lg493t517q641l5gcm340000gn/T/AppTranslocation/FD570E09-4B60-4611-9E38-14148D7EDC0D/d/oss-browser.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/var/folders/ds/m1z5lg493t517q641l5gcm340000gn/T/AppTranslocation/FD570E09-4B60-4611-9E38-14148D7EDC0D/d/oss-browser.app/Contents/Resources/app.asar/main.js:15:11)
    at Object.<anonymous> (/private/var/folders/ds/m1z5lg493t517q641l5gcm340000gn/T/AppTranslocation/FD570E09-4B60-4611-9E38-14148D7EDC0D/d/oss-browser.app/Contents/Resources/app.asar/main.js:289:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

 v1.10.0-alpha
PeterRao released this 27 days ago
Merge pull request #274 from aliyun/fix/cleanfile
chore: remove useless file

**Comment by k3mlol** [comment]
我也是。我还把旧的删除了。。。

**Comment by PeterRao** [comment]
下载 https://help.aliyun.com/document_detail/61872.html?spm=5176.8465980.0.0.4e701450Kn7Wve 试下。

**Comment by k3mlol** [comment]
> 下载 https://help.aliyun.com/document_detail/61872.html?spm=5176.8465980.0.0.4e701450Kn7Wve 试下。

mac catalina 可以使用的，蟹蟹

**Comment by hongweipeng** [comment]
![微信截图_20200221210644](https://user-images.githubusercontent.com/7546325/75036998-1df88f80-54ee-11ea-95be-974227057f81.png)

windows 也无法启动。

**Comment by PeterRao** [comment]
下载 https://help.aliyun.com/document_detail/61872.html?spm=5176.8465980.0.0.4e701450Kn7Wve 试下。

**Comment by jinmingjiaoyu** [comment]
> 下载 https://help.aliyun.com/document_detail/61872.html?spm=5176.8465980.0.0.4e701450Kn7Wve 试下。

试锤子
